default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  port: <%= ENV["DB_PORT"] || 5432 %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] || "my_app_development" %>

test:
  <<: *default
  database: <%= ENV["DB_NAME_TEST"] || "my_app_test" %>

production:
  <<: *default
  database: <%= ENV["DB_NAME_PRODUCTION"] %>
  username: <%= ENV["DB_USERNAME_PRODUCTION"] %>
  password: <%= ENV["DB_PASSWORD_PRODUCTION"] %>
  host: <%= ENV["DB_HOST_PRODUCTION"] || "localhost" %>
  port: <%= ENV["DB_PORT_PRODUCTION"] || 5432 %>
